FROM node:14.14.0-alpine
WORKDIR '/app'
RUN npm install -g yarn
COPY ./package.json ./
RUN yarn install
COPY . .

CMD ["yarn", "start"]

EXPOSE 3000

# RUN npm run build

# FROM nginx
# EXPOSE 3000
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=0 /app/build /usr/share/nginx/html