FROM node:14.16.0-alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .

CMD ["npm", "run", "start"]

EXPOSE 3000

# RUN npm run build

# FROM nginx
# EXPOSE 3000
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=0 /app/build /usr/share/nginx/html